[package]
name = "td"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
clap = { version = "3.1.9", features = ["derive"] }
=======
    clap = { version = "3.1.9", features = ["derive"] }
    thiserror = "1.0.30"
>>>>>>> 8be64b932020a956ffdc8b21d323b8e8033a2886
